development:
  adapter: postgresql
  encoding: unicode
  database: mydb
  pool: 2
  username: postgres
  password: Landof0oo!

production:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 2
  username: your_username
  password: your_password
